import "../globals.css";
import Link from "next/link";
import ApplicantLayout from './ApplicantLayout'

export const metadata= {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
      <div>
        <ApplicantLayout>
          {children}
        </ApplicantLayout>
      </div>
  );
}
